name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deps
        run: ./scripts/deps.sh
      - name: Package
        run: ./scripts/build.sh
      - name: Deploy
        id: deploy
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: "deploy --require-approval never"
          cdk_stack: "*"
          actions_comment: false
          working_dir: "infra"
          args: ""
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
      - name: Check deploy status
        if: job.steps.deploy.status == failure()
        run: exit 1
