name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Cache rust build
        uses: actions/cache@v2
        with:
          path: |
            target
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Deps
        run: ./scripts/deps.sh
      - name: Package
        run: ./scripts/build.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lambdas
          path: |
            target/lambda-api.zip
            target/lambda-authorizer.zip
      - name: Deploy
        id: deploy
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: "deploy --require-approval never"
          cdk_stack: "*"
          actions_comment: false
          working_dir: "infra"
          args: ""
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
          OPENID_AUD: ${{ secrets.OPENID_AUD }}
          OPENID_CONFIG_URI: ${{ secrets.OPENID_CONFIG_URI }}
